### ISSUE TITLE
[Feat] userService.createUser에서 데이터베이스에 유저가 생성될 경우, 메모리 유저도 생성 (this.memoryUserService.addUser() 호출)

### ISSUE THREAD

**Issue by brixxt27** [5GoInMul-Transcendence/ft_transcendence#107]
# Issue 생성 전 체크리스트
- [x] 이슈 이름은 다른 사람도 이해할 수 있나요?
- [x] 이슈 책임자(Assignees)를 추가했나요?
- [x] Labels에는 해당 이슈의 성향을 잘 나타내나요?
- [x] 해당 Issue가 파트(front-end 또는 back-end)에 종속된다면 Labels에 파트를 표시했나요?

# Description
- 

# To do
- [ ]

**Comment by reg0145** [comment]
- #99
  - 위 이슈에서 UserService에 memoryUser를 주입받는 코드를 작성하였습니다. 참고바랍니다.

**Comment by brixxt27** [comment]
@reg0145 확인! 
자나깨나 pull 조심
최근 브랜치라도 pull 하고 건너 가자
