### ISSUE TITLE
[Feat] oauth 로그인 성공후 localhost:3000/main으로 리다이렉트 처리하기

### ISSUE THREAD

**Issue by reg0145** [5GoInMul-Transcendence/ft_transcendence#157]
# Issue 생성 전 체크리스트
- [ ] 이슈 이름은 다른 사람도 이해할 수 있나요?
- [ ] 이슈 책임자(Assignees)를 추가했나요?
- [ ] Labels에는 해당 이슈의 성향을 잘 나타내나요?
- [ ] 해당 Issue가 파트(front-end 또는 back-end)에 종속된다면 Labels에 파트를 표시했나요?

# Description
## 클라이언트가 브라우저를 통해 http://localhost:3000/login 에서 42 O-Auth로 로그인할 때의 시나리오
- 42로 로그인 클릭
- front 는 back 으로 GET http://localhost:8080/login/oauth/42 로 요청을 보냄
- back 컨트롤러에 있는 Guard 에서 42 intra 로그인 페이지 http://api.42~client-key~client-secret~ 로 리다이렉션 함
- 로그인을 실패하면 42 로그인 페이지에 리다이렉션 된 상태로 끝난다. 왜냐하면 42 로그인 페이지에 리다이렉션 되면 우리 서버의 관할을 벗어났기 때문이다. 프론트와 백의 관계를 좀 더 알기 전에는 42 로그인에 실패했을 때 우리 서버는 응답을 보내주지 않아서 그러나 보다 하고 넘어갔는데 리다이렉션을 통해 통제권 자체를 42에 준 것이기 때문에 우리 서버는 클라이언트에 응답을 보내지 못하고 끝나는 것이었다.
- 로그인에 성공하면 42는 http://localhost:8080/login/oauth/42/redirect 로 리다이렉션 시킨다. 원래는 프론트 페이지를 보고 있을 터인데 백 서버에 직접 리다이렉션 되었기 때문에 서버가 별다른 처리를 하지 않으면 클라이언트는 서버의 리소스를 보게 된다. 사실 상 클라이언트는 서버의 리소스를 보는 것은 의미가 없고, 보안 상의 이유로도 그러면 안 된다.
- 서버는 사전에 필요한 정보를 42에 요청하면서 리다이렉션 했었고, 이 시점에는 42에게 그 정보를 받은 상태다. 유일한 profile id 를 이용해 회원가입 또는 로그인을 진행하고, 원래라면 {"data": {}, "resStatus": {"code" : "1234", "message" : abcd"}} JSON 데이터를 반환하고 끝내려 했다. 그러나 서버 리소스에 리다이렉션 되었으므로 이 JSON 을 반환한다 해도 프론트는 받을 수 없고, 클라이언트는 브라우저 상에서 해당 데이터를 그대로 보게 된다.
- 이를 해결하기 위해서 회원가입/로그인 로직을 진행했으니 서버에서도 42가 했던 것처럼 프론트로 리다이렉션 보내줘야 한다.
- 리다이렉션 되면 URL 에 있는 정보와 Req 의 헤더에 있는 정보를 제외한 body 에 있는 데이터는 없어진다. 그렇기 때문에 평소 API 응답으로 보내는 형식으로 반환하면 프론트는 해당 정보를 받을 수 없다. 때문에 로그인 이후 프론트가 리다이렉션 시켜줄 페이지로 서버가 직접 리다이렉션 시켜줘야 한다. 그게 http://localhost:3000/main 이다.

# To do
- [ ]

**Comment by brixxt27** [comment]
#178 해결함
