### ISSUE TITLE
[Feat] *모두 나에게 의견을 줘~~* 채팅 수정 요구 사항(만나서 같이 맞춰보는 것으로!)

### ISSUE THREAD

**Issue by brixxt27** [5GoInMul-Transcendence/ft_transcendence#201]
# Issue 생성 전 체크리스트
- [ ] 이슈 이름은 다른 사람도 이해할 수 있나요?
- [ ] 이슈 책임자(Assignees)를 추가했나요?
- [ ] Labels에는 해당 이슈의 성향을 잘 나타내나요?
- [ ] 해당 Issue가 파트(front-end 또는 back-end)에 종속된다면 Labels에 파트를 표시했나요?

# Description [API 명세서는 여기를 클릭하세요!](https://42-transcendence.gitbook.io/42_transcendence/api-reference/undefined-4/undefined)

### 요구 사항
- [ ] recentMessage 에서 message 프로퍼티 명을 content 로 변경 요청!
- 소스 상에서 {id, user, content, timestamp} 를 가지고 있는 message 라는 객체가 이미 있는데 메시지 내용도 message 라고 해버리니까 헷갈려 돌아버림~
- 이미 다른 API 와 소켓 명세서에서도 전부 content 로 되어 있음. 얘만 왕따임. 이를 통일하기 위해 변경하는 것이 좋아 보임

## 모든 채널 생성 모드마다 API 따로 만들기
- [x] POST /channel/publc
- [x] POST /channel/protected
- [x] POST /channel/private
- [x] POST /channel/dm API 새롭게 생성
- 기존 dm 은 누구에게 dm을 할 것인지에 대한 정보가 없어서 기존 채팅방 생성과 같다고 생각했는데 우리가 의도한 것은 한 명이 dm 방을 만들면 자연스럽게 다른 한 명이 해당 방에 초대 되어 my channel 이 되는 것이다. 때문에 dm 방에 초대할 유저의 userId 를 body 에 담아 따로 채널을 만들어야 한다.
- 기존 채널 API 를 재활용 하기엔 초대할 유저 이름을 처음부터 적는 경우는 dm밖에 없어 비효율적임
# To do
- [ ]

**Comment by reg0145** [comment]
![image](https://github.com/5GoInMul-Transcendence/ft_transcendence/assets/90084199/7e43aa58-5e39-48c4-ad70-f0583871fd5f)

**Comment by brixxt27** [comment]
![image](https://github.com/5GoInMul-Transcendence/ft_transcendence/assets/83959536/57384f22-3bc6-4ff5-a8ee-e5ae03629a9d)

@kjy00 위와 같이 dm 보낼 시 초대할 유저의 id(숫자) 를 보내줄 수 있나요?
