### ISSUE TITLE
[Bug] 채팅 페이지 수정사항

### ISSUE THREAD

**Issue by Arkingco** [5GoInMul-Transcendence/ft_transcendence#263]
# Issue 생성 전 체크리스트
- [ ] 이슈 이름은 다른 사람도 이해할 수 있나요?
- [ ] 이슈 책임자(Assignees)를 추가했나요?
- [ ] Labels에는 해당 이슈의 성향을 잘 나타내나요?
- [ ] Labels에는 자신의 파트(front-end 또는 back-end)를 잘 나타내나요?
- [ ] 해당 Issue가 파트(front-end 또는 back-end)에 종속된다면 Labels에 파트를 표시했나요?

# Description
- 채팅 페이지에서 발생하는 문제를 하나씩 작성해보자

# To do
- [x] 채팅방 메시지가 undefined로 되어있음
<img width="233" alt="스크린샷 2023-09-18 오후 7 16 56" src="https://github.com/5GoInMul-Transcendence/ft_transcendence/assets/28525747/e5f729f8-2743-4b97-ba29-259c31779178">

- [x] 처음 채팅방에 들어갔을 때 내가 보낸 메시지가 왼쪽에 나오는 문제
<img width="1424" alt="image" src="https://github.com/5GoInMul-Transcendence/ft_transcendence/assets/83959536/7f61035b-f4bf-4707-b9b5-fe8ca88b69cb">

- [ ] my channel list 에 있는 protected 를 all 또는 my 에서 다시 들어가려 할 때 비밀번호를 물어봄
- [ ] protected mode 방을 생성한 뒤 누군가 들어오면 all list 에 하나 더 생김
- [ ] 기존에 들어간 채널이 아닌 protected 방을 비밀번호를 치고 들어간 뒤, all, my, all, my... 를 번갈아 치면 채널이 증식함
- [ ] 채널 유저 설정에서 admin 으로 변경 시 3000 포트로 요청 보냄
- [ ] 새로고침 하지 않으면 my list 에 최신 메시지 보이지 않음
<img width="813" alt="image" src="https://github.com/5GoInMul-Transcendence/ft_transcendence/assets/83959536/a953cb4d-d4ec-41b3-b813-c743c0f3f96c">

- [ ] 새로고침하면 채널에 메시지가 있음에도 불구하고 undefined 나옴

**Comment by reg0145** [comment]
<img width="428" alt="스크린샷 2023-09-20 오후 10 25 12" src="https://github.com/5GoInMul-Transcendence/ft_transcendence/assets/90084199/b377a573-fd01-4ed4-bf6a-2be1fb69a035">

Game 버튼 무반응

**Comment by reg0145** [comment]
<img width="493" alt="스크린샷 2023-09-20 오후 10 57 09" src="https://github.com/5GoInMul-Transcendence/ft_transcendence/assets/90084199/9784c126-0fa4-49b0-be1d-64c2c93e57aa">

Ban 클릭시 Mute 활성화

**Comment by brixxt27** [comment]
<img width="1169" alt="image" src="https://github.com/5GoInMul-Transcendence/ft_transcendence/assets/83959536/d3d7b71e-ccc1-4590-ae69-a900f24bfafb">

- 자신에게 적용 시킬 수 없습니다라는 에러 모달이 뜨지 않습니다!

**Comment by Arkingco** [comment]
> <img alt="image" width="1169" src="https://user-images.githubusercontent.com/83959536/269309019-d3d7b71e-ccc1-4590-ae69-a900f24bfafb.png">
> * 자신에게 적용 시킬 수 없습니다라는 에러 모달이 뜨지 않습니다!

해당하는 부분은 모달이라 메시지가 모달 내부에 표시가 되게끔 만들겠습니다.

모달 안에서 뜬 에러 -> setinvalid msg 업데이트 및 빨간색 글씨로 나옴
모달 밖에서 뜬 에러 -> 모달이 켜지고 setinvalid msg업데이트 켜진 모달에 빨간색 끌시로 나옴 
로 관리 됩니다!
