### ISSUE TITLE
[Chore] Update structure of directory about users

### ISSUE THREAD

**Issue by brixxt27** [5GoInMul-Transcendence/ft_transcendence#72]
# Issue 생성 전 체크리스트
- [x] 이슈 이름은 다른 사람도 이해할 수 있나요?
- [x] 이슈 책임자(Assignees)를 추가했나요?
- [x] Labels에는 해당 이슈의 성향을 잘 나타내나요?
- [x] 해당 Issue가 파트(front-end 또는 back-end)에 종속된다면 Labels에 파트를 표시했나요?

# Description
@reg0145 
<img width="296" alt="image" src="https://github.com/5GoInMul-Transcendence/ft_transcendence/assets/83959536/da789846-6215-4d80-abdc-1ffbb66fd196">
## 문제점
-  기존 user 에서 memoryUser 가 생기면서 users 라는 디렉토리가 생겼습니다. users 내에는 크게 두 개의 주요 class, user, memoryUser 가 있습니다. 이 때 user 에 대한 dto 또는 entity 를 찾으려면 그 바깥의 users 디렉토리에서 찾아야하고, memoryUser 의 필요한 데이터를 찾으려면 또 하나의 디렉토리 depth 를 나와 users 에서 찾아야합니다!
- entity 또는 dto 디렉토리에서 특정 파일을 찾는 데 이름이 명시적이고, 의미를 완전히 담으면 우리끼리는 괜찮을 거라 생각합니다. 근데 미래의 우리가 보거나 다른 사람이 볼 때면 이 데이터 명세서(class) 가 user의 것인가? memoryUser의 것인가? 를 놓고 본다면 헷갈릴 것 같습니다!
## 요청 사항
- user 와 memoryUser 각각 자신의 디렉토리 내에 사용하는 dto 와 entity 를 가지도록 하는 것은 어떤가요?

# To do
- [ ]

**Comment by reg0145** [comment]
좋습니다. 그 부분은 따로 pull request를 만들어 작업을 하면 좋겠네요

**Comment by eesum** [comment]
왔다감
