### ISSUE TITLE
[Chore] user 디렉토리 구조 원복 요청

### ISSUE THREAD

**Issue by brixxt27** [5GoInMul-Transcendence/ft_transcendence#83]
# Issue 생성 전 체크리스트
- [x] 이슈 이름은 다른 사람도 이해할 수 있나요?
- [x] 이슈 책임자(Assignees)를 추가했나요?
- [x] Labels에는 해당 이슈의 성향을 잘 나타내나요?
- [x] 해당 Issue가 파트(front-end 또는 back-end)에 종속된다면 Labels에 파트를 표시했나요?

# Description
@reg0145
<img width="331" alt="image" src="https://github.com/5GoInMul-Transcendence/ft_transcendence/assets/83959536/aabdae5b-c5e8-431e-9be1-357047f310be">
- user 와 me, memoryUser 의 관계를 몰랐을 때는 user 디렉토리 명을 users 로 변경한 후 user 디렉토리를 새로 생성하여 따로 빼는 게 최선으로 보였는데 현재는 원복하는 게 좋아보입니다. 즉, users 가 아닌 user 디렉토리 안에 me, memoryUser 가 존재! 이유는 다음과 같습니다.
    - UserModule 이 me controller 를 controller 로 가지고 있다.
    - UserModule 이 MemoryUserService 및 provider 를 provider 로 가지고 있다.
- 이들을 포함하는 모듈 단위가 user 라는 디렉토리에 들어가 있으면 이 관계를 효과적으로 표현하지 못한다 생각합니다!

# To do
- [ ]

**Comment by reg0145** [comment]
네 좋습니다. 다만 이부분은 이슈로 남겨두고 나중에 API 구현이 끝난 뒤 리팩토링 단계에서 진행을 하면 좋을 것 같습니다.
